---
title: "1.3_Pmea.Procrustes"
output: html_document
date: "2023-04-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Load libraries
```{r, include = FALSE}
library(dartR)
library(adegenet)
library(poppr)
library(hierfstat)
library(reshape2)
library(ggplot2)
library(RColorBrewer)
library(scales)
library(dplyr)
```


```{r}
#for this purpose, we only want CSMP samples to match with the symbiont samples 
gl <- gl.read.dart(filename = "../Report_DPoc22-7167_SNP_mapping_2.csv", covfilename = "Pmea_CSMPonly_LIMS.csv")

gl <- gl.drop.ind(gl,
  ind.list=c('P ver 221', 'P ver 371', 'P ver 372', 'P ver 291', 'P ver 044'))

gl <- gl.drop.pop(gl, 
                  pop.list = "Corbett")

m <- as.matrix(gl)
```

```{r}
#filter to gl3 parameters for the csmp subset. 
gl <- gl.filter.secondaries(gl)
nLoc(gl)
#27,253 loci 

#filter loci with reproducibility below a particular threshold
gl.report.reproducibility(gl)
gl <- gl.filter.reproducibility(gl, threshold = 0.98)

nLoc(gl)
#21992 loci 

#filter loci with >5% missing data. this is standard. Note that this is different call rate filter to the regional based on we are only looking at Coral Sea here 
gl2 <- gl.filter.callrate(gl, method = "loc", threshold = 0.80)
nLoc(gl2)
#2462 loci 
gl.report.callrate(gl2)

#filter read depth < 5x
gl2 <- gl.filter.rdepth(gl2, lower = 5, upper = 200, verbose = 3)
nLoc(gl2)
#2429 SNPs remaining 
```

##MAF filtering 
```{r}
#We will filter out loci with a MAF less than 0.05.**
gl3.csmp.pmea <- gl.filter.maf(gl2, threshold = 0.95) 

#report for MAF after filtering with MAF < 0.05 
gl.report.maf(gl3.csmp.pmea)
nLoc(gl3.csmp.pmea)
#1951 SNPs remaining 

gl3.csmp.pmea <- gl.impute(
  gl3.csmp.pmea,
  method = "neighbour",
  fill.residual = TRUE,
  parallel = FALSE,
  verbose = NULL
)

nInd(gl3.csmp.pmea)

#save(gl3.csmp.pmea, file = "gl3.csmp.pmea.RData")

indNames(gl3.csmp.pmea)
```



#Admixture plots 
```{r}
library(LEA)
## Here we are moving on to the LEA package in order to estimate K clusters and create admixture plots 
```

```{r}
gl2geno(gl3.csmp.pmea, outfile = "gl_geno", outpath = getwd(), verbose = NULL)
```

```{r, include = FALSE}
pc = pca("gl_geno.lfmm", scale = TRUE)
tw = tracy.widom(pc)

#Plots the percentage of variance explained by eah component. You can look at the 'elbow' to inform the number of genetic clusers. It looks like ours is between 3-5.
plot(tw$percentage, pch = 19, col = "darkblue", cex = .8)
```


#Run snmf algorithm
```{r, include = FALSE}
snmf1 = snmf("gl_geno.geno",
        K = 1:10,    #number of K ancestral populations to run
        entropy = TRUE,     #calculate cross-entropy
        repetitions = 10,    #10 repetitions for each K
        project = "new")

plot(snmf1, col = "blue", cex = 1.5, pch = 19)
```


```{r}
# Extract the cross-entropy of all runs where K = 2
ce = cross.entropy(snmf1, K = 2)
ce

lowest.ce = which.min(ce)
lowest.ce
```

```{r}
qmatrix = as.data.frame(Q(snmf1, K = 2, run = lowest.ce))
head(qmatrix)

# Label column names of qmatrix
ncol(qmatrix)
cluster_names = c()
for (i in 1:ncol(qmatrix)){
  cluster_names[i] = paste("Cluster", i)
}
cluster_names
colnames(qmatrix) = cluster_names
head(qmatrix)

qmatrix
```


```{r}
# Add individual IDs
qmatrix$Ind = indNames(pmea_gen)

#Add site IDs
qmatrix$Site = pmea_gen$pop
head(qmatrix)

#Convert dataframe to long format
qlong = melt(qmatrix, id.vars=c("Ind","Site"))
head(qlong)

qlong.pmea <- qlong %>% dplyr::filter(variable == "Cluster 1") %>% 
    select(Ind, admix1 = value)

save(qlong.pmea, file = "qlong.pmea.RData")
```
