---
title: "1.2_Procrustes_C3"
output: html_document
date: "2023-05-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load libraries
```{r, include=FALSE}
library(dartR)
library(adegenet)
library(poppr)
library(hierfstat)
library(reshape2)
library(ggplot2)
library(RColorBrewer)
library(scales)
library(dplyr)
```


```{r, include = FALSE}
#we are loading the dart SNP file (first file) and the metadata that has the individuals and the population they were sampled from

gl <- gl.read.dart(filename = "Report_DAc22-6709_SNP_mapping_2.csv", covfilename = "Ahum_CSMP_LIMS.csv")

gl <- gl.drop.ind(gl, 
                    ind.list= c("A ten 271", "A ten 289"))

#dropping individuals that have high admixture fronm the two uncommon clusters 
#cluster 1
gl <- gl.drop.ind(gl, 
                    ind.list= c("A ten 018", "A ten 274", "A ten 280", "A ten 285", "A ten 024", "A ten 287", "A ten 037", "A ten 025", "A ten 026", "A ten 040", "A ten 271", "A ten 041", "A ten 030", "A ten 273", "A ten 042", "A ten 234", "A ten 044", "A ten 272", "A ten 045", "A ten 028", "A ten 284", "A ten 034", "A ten 288", "A ten 290", "A ten 270", "A ten 286", "A ten 017", "A ten 291", "A ten 277", "A ten 048", "A ten 281"))

#dropping individuals from cluster 2
gl <- gl.drop.ind(gl,
                   ind.list = c("A ten 100", "A ten 089", "A ten 023", "A ten 090", "A ten 092", "A ten 256", "A ten 085", "A ten 094", "A ten 068", "A ten 086", "A ten 087", "A ten 099", "A ten 083", "A ten 093", "A ten 019", "A ten 177", "A ten 279", "A ten 300", "A ten 246", "A ten 305", "A ten 254", "A ten 255", "A ten 171", "A ten 252"))

#dropping 4 more individuals that are outliers after re-filtering 
gl <- gl.drop.ind(gl,
                    ind.list = c("A ten 051", "A ten 052", "A ten 144", "A ten 130"))

m <- as.matrix(gl)
```



```{r}
#filter to gl3 parameters for the csmp subset. 
gl <- gl.filter.secondaries(gl)
nLoc(gl)

#filter loci with reproducibility below a particular threshold
gl.report.reproducibility(gl)
gl <- gl.filter.reproducibility(gl, threshold = 0.98)

nLoc(gl)

#filter loci with >5% missing data. this is standard. Note that this is different call rate filter to the regional based on we are only looking at Coral Sea here 
gl2 <- gl.filter.callrate(gl, method = "loc", threshold = 0.90)
nLoc(gl2)


gl.report.callrate(gl2)

#filter read depth < 5x
gl2 <- gl.filter.rdepth(gl2, lower = 5, upper = 200, verbose = 3)
nLoc(gl2)

```

##MAF filtering 
```{r}
#We will filter out loci with a MAF less than 0.05.**
gl3.csmp.acroC3 <- gl.filter.maf(gl2, threshold = 0.95) 

#report for MAF after filtering with MAF < 0.05 
gl.report.maf(gl3.csmp.acroC3)
nLoc(gl3.csmp.acroC3)
#1951 SNPs remaining 

gl3.csmp.acroC3 <- gl.impute(
  gl3.csmp.acroC3,
  method = "neighbour",
  fill.residual = TRUE,
  parallel = FALSE,
  verbose = NULL
)

nInd(gl3.csmp.acroC3)

#save(gl3.csmp.pmea, file = "gl3.csmp.pmea.RData")

list.acroC3 <- indNames(gl3.csmp.acroC3)
save(list.acroC3, file = "list.acroC3.RData")

save(gl3.csmp.acroC3, file = "gl3.csmp.acroC3.RData")
```




#Admixture plots 
```{r}
library(LEA)
## Here we are moving on to the LEA package in order to estimate K clusters and create admixture plots 
```

##Converting to a genlight object for downstream analysis 
```{r}
#converting a genlight object (we have) to a genind object so we can look at genetic data at an individual data using adegenet package. 
acro_genC3 <- gl2gi(gl3.csmp.acroC3, probar = FALSE, verbose = NULL)
acro_genC3

is.genind(acro_genC3)
```

```{r}
gl2geno(gl3.csmp.acroC3, outfile = "gl_geno", outpath = getwd(), verbose = NULL)
```

```{r, include = FALSE}
pc = pca("gl_geno.lfmm", scale = TRUE)
tw = tracy.widom(pc)

#Plots the percentage of variance explained by eah component. You can look at the 'elbow' to inform the number of genetic clusers. It looks like ours is between 3-5.
plot(tw$percentage, pch = 19, col = "darkblue", cex = .8)
```


#Run snmf algorithm
```{r, include = FALSE}
snmf1 = snmf("gl_geno.geno",
        K = 1:10,    #number of K ancestral populations to run
        entropy = TRUE,     #calculate cross-entropy
        repetitions = 10,    #10 repetitions for each K
        project = "new")

plot(snmf1, col = "blue", cex = 1.5, pch = 19)
```


```{r}
# Extract the cross-entropy of all runs where K = 2
ce = cross.entropy(snmf1, K = 3)
ce

lowest.ce = which.min(ce)
lowest.ce
```

```{r}
qmatrix = as.data.frame(Q(snmf1, K = 2, run = lowest.ce))
head(qmatrix)

# Label column names of qmatrix
ncol(qmatrix)
cluster_names = c()
for (i in 1:ncol(qmatrix)){
  cluster_names[i] = paste("Cluster", i)
}
cluster_names
colnames(qmatrix) = cluster_names
head(qmatrix)

qmatrix
```




```{r}
# Add individual IDs
qmatrix$Ind = indNames(acro_genC3)

#Add site IDs
qmatrix$Site = acro_genC3$pop
head(qmatrix)

#Convert dataframe to long format
qlong = melt(qmatrix, id.vars=c("Ind","Site"))
head(qlong)

qlong.acroC3 <- qlong %>% dplyr::filter(variable == "Cluster 1") %>% 
    select(Ind, Admix1 = value)

save(qlong.acroC3, file = "qlong.acroC3.RData")
```