---
title: "1.2_Procrustes"
output: html_document
date: "2023-05-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load libraries
```{r, include=FALSE}
library(dartR)
library(adegenet)
library(poppr)
library(hierfstat)
library(reshape2)
library(ggplot2)
library(RColorBrewer)
library(scales)
library(dplyr)
```


```{r, include = FALSE}
gl <- gl.read.dart(filename = "Report_DAc22-6709_SNP_mapping_2.csv", covfilename = "Ahum_CSMP_LIMS.csv")

gl <- gl.drop.ind(gl, 
                    ind.list= c("A ten 271", "A ten 289"))

m <- as.matrix(gl)
```



```{r}
#filter to gl3 parameters for the csmp subset. 
gl <- gl.filter.secondaries(gl)
nLoc(gl)

#filter loci with reproducibility below a particular threshold
gl.report.reproducibility(gl)
gl <- gl.filter.reproducibility(gl, threshold = 0.98)

nLoc(gl)

#filter loci with >5% missing data. this is standard. Note that this is different call rate filter to the regional based on we are only looking at Coral Sea here 
gl2 <- gl.filter.callrate(gl, method = "loc", threshold = 0.90)
nLoc(gl2)


gl.report.callrate(gl2)

#filter read depth < 5x
gl2 <- gl.filter.rdepth(gl2, lower = 5, upper = 200, verbose = 3)
nLoc(gl2)

```

##MAF filtering 
```{r}
#We will filter out loci with a MAF less than 0.05.**
gl3.csmp.acro <- gl.filter.maf(gl2, threshold = 0.95) 

#report for MAF after filtering with MAF < 0.05 
gl.report.maf(gl3.csmp.acro)
nLoc(gl3.csmp.acro)
#1951 SNPs remaining 

gl3.csmp.acro <- gl.impute(
  gl3.csmp.acro,
  method = "neighbour",
  fill.residual = TRUE,
  parallel = FALSE,
  verbose = NULL
)

nInd(gl3.csmp.acro)

#save(gl3.csmp.pmea, file = "gl3.csmp.pmea.RData")

list.acro <- indNames(gl3.csmp.acro)
save(list.acro, file = "list.acro.RData")

save(gl3.csmp.acro, file = "gl3.csmp.acro.RData")
```

##Converting to genlight 
```{r}
#converting a genlight object (we have) to a genind object so we can look at genetic data at an individual data using adegenet package. 
acro_gen <- gl2gi(gl3.csmp.acro, probar = FALSE, verbose = NULL)
acro_gen

#// 148 individuals; 3,270 loci; 6,540 alleles; size: 35 Mb

is.genind(acro_gen)
```


##2.3 Check monomorphic loci 
```{r}
#check that loci are still polymorphic after filtering. Retaining monomorphic loci unnecessarily increases the size of the dataset and will affect some calculations.

isPoly(acro_gen) %>% summary

#remove loci that are not polymorphic 

poly_loci = names(which(isPoly(acro_gen) == TRUE))
acro_gen = acro_gen[loc = poly_loci]
isPoly(acro_gen) %>% summary
```


##4.1 PCA model 
```{r}
x = tab(acro_gen, NA.method = "mean")

# Perform PCA
pca1 = dudi.pca(x, scannf = FALSE, scale = FALSE, nf = 3)

# Analyse how much percent of genetic variance is explained by each axis
percent = pca1$eig/sum(pca1$eig)*100
barplot(percent, ylab = "Genetic variance explained by eigenvectors (%)", ylim = c(0,12),
        names.arg = round(percent, 1))
```



##4.2 PCA coord dataframe 
```{r}
# Create a data.frame containing individual coordinates
ind_coords = as.data.frame(pca1$li) 

# Rename columns of dataframe
colnames(ind_coords) = c("Axis1","Axis2","Axis3")

# Add a column containing individuals
ind_coords$Ind = indNames(acro_gen)

# Add a column with the site IDs
ind_coords$Site = acro_gen$pop

# Calculate centroid (average) position for each population
centroid = aggregate(cbind(Axis1, Axis2, Axis3) ~ Site, data = ind_coords, FUN = mean)

# Add centroid coordinates to ind_coords dataframe
ind_coords = left_join(ind_coords, centroid, by = "Site", suffix = c("",".cen"))

# Define colour palette
cols = brewer.pal(nPop(acro_gen), "Set3")

# Custom x and y labels
xlab = paste("Axis 1 (", format(round(percent[1], 1), nsmall=1)," %)", sep="")
ylab = paste("Axis 2 (", format(round(percent[2], 1), nsmall=1)," %)", sep="")
```


##4.3 PCA metadata 
```{r}
acro_meta <- meta_acro %>% 
  tibble::rownames_to_column(var = "Ind") %>% 
  dplyr::select(c(Ind, Reef)) 

ind_coords.acro <- ind_coords %>% left_join(acro_meta) %>% 
  mutate(Reef = as.factor(Reef))

```


##4.4 Theme for PCA
```{r}
theme_PCA <-theme(aspect.ratio = 3/5) +
  theme(axis.line = element_blank()) +
  theme(plot.background = element_blank(),
    panel.background = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank()) +
 theme(panel.border = element_rect(colour = "black", fill=NA, linewidth=1))
```


##4.5 Plot PCA by sector
```{r}
ind_coords.acro

ind_coords.acro <- ind_coords.acro %>% mutate(Site = factor(Site, levels = c("Osprey", "Bougainville", "Moore", "Willis", "Holmes", "Chilcott", "Herald","Lihou", "Flinders", "Marion", "Frederick", "Saumarez", "Wreck")))


PCA_acro <- ind_coords.acro %>% 
  ggplot(aes(Axis1, Axis2, fill = Site)) +
  geom_point(alpha = 1, shape = 21, size = 2) + 
#  scale_fill_manual(values = ) +
  labs(x = xlab, y = ylab) +
  theme_PCA

PCA_acro
```

#Admixture plots 
```{r}
library(LEA)
## Here we are moving on to the LEA package in order to estimate K clusters and create admixture plots 
```

```{r}
gl2geno(gl3.csmp.acro, outfile = "gl_geno", outpath = getwd(), verbose = NULL)
```

```{r, include = FALSE}
pc = pca("gl_geno.lfmm", scale = TRUE)
tw = tracy.widom(pc)

#Plots the percentage of variance explained by eah component. You can look at the 'elbow' to inform the number of genetic clusers. It looks like ours is between 3-5.
plot(tw$percentage, pch = 19, col = "darkblue", cex = .8)
```


#Run snmf algorithm
```{r, include = FALSE}
snmf1 = snmf("gl_geno.geno",
        K = 1:10,    #number of K ancestral populations to run
        entropy = TRUE,     #calculate cross-entropy
        repetitions = 10,    #10 repetitions for each K
        project = "new")

plot(snmf1, col = "blue", cex = 1.5, pch = 19)
```


```{r}
# Extract the cross-entropy of all runs where K = 2
ce = cross.entropy(snmf1, K = 3)
ce

lowest.ce = which.min(ce)
lowest.ce
```

```{r}
qmatrix = as.data.frame(Q(snmf1, K = 3, run = lowest.ce))
head(qmatrix)

# Label column names of qmatrix
ncol(qmatrix)
cluster_names = c()
for (i in 1:ncol(qmatrix)){
  cluster_names[i] = paste("Cluster", i)
}
cluster_names
colnames(qmatrix) = cluster_names
head(qmatrix)

qmatrix
```


```{r}
# Add individual IDs
qmatrix$Ind = indNames(acro_gen)

#Add site IDs
qmatrix$Site = acro_gen$pop
head(qmatrix)

#Convert dataframe to long format
qlong = melt(qmatrix, id.vars=c("Ind","Site"))
qlong

```



##6.7 Admixture faceted by sector
```{r}
library(forcats)

# Reorder factor levels within groups
qlong <- qlong %>%
  group_by(variable) %>%
  mutate(Ind = fct_reorder(Ind, value, .desc = TRUE)) %>%
  arrange(variable, Ind)

qlong <- qlong %>% mutate(variable = factor(variable, levels = c("Cluster 1", "Cluster 2", "Cluster 3")))#%>% 
 # mutate(variable = recode(variable, "Cluster 1" = "PVCL1", "Cluster 2" = "PVCL2"))

# Relevel the "Site" variable
qlong$Site <- forcats::fct_relevel(qlong$Site, "Osprey", "Bougainville", "Moore", "Willis", "Holmes", "Chilcott", "Herald","Lihou", "Flinders", "Marion", "Frederick", "Saumarez", "Wreck")

# Relevel the "Ind" variable by the "Site" variable in the data frame
qlong$Ind <- factor(qlong$Ind, levels = unique(qlong$Ind[order(qlong$Site)]))


admix.fig <- ggplot(qlong, aes(x = Ind, y = value, fill = variable)) +
  geom_col(color = "gray", linewidth = 0.1, width = 1) +
  facet_grid(~ Site, scales = "free_x", space = "free_x", switch = "x") +
  theme_minimal() +
  scale_fill_manual(values = cols) +
  labs(x = "Individual", y = "Admixture Proportion") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_discrete(expand = c(0, 0)) +
  theme(
    panel.spacing.x = unit(0.1, "lines"),
    panel.grid = element_blank(),
    axis.text.x = element_blank(),
    strip.text = element_text(colour = "black", size = 6),
    panel.background = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    plot.margin = margin(t = 30, r = 10, b = 30, l = 10, unit = "mm"),
    panel.border = element_rect(color = "black", fill = NA, size = 0.5)
  )

admix.fig
```




```{r}
#assigning each sample as one of the 3 clusters, whichever is > 50% of sample proportion 
qlong
qlongC1 <- qlong %>% dplyr::filter(variable == "Cluster 1") %>% 
  filter(value > 0.5)

qlongC2 <- qlong %>% dplyr::filter(variable == "Cluster 2") %>% 
  filter(value > 0.5)

qlongC3 <- qlong %>% dplyr::filter(variable == "Cluster 3") %>% 
  filter(value > 0.5)

qlongC1C2 <- qlongC1 %>% full_join(qlongC2)

qlong.acro <- qlongC1C2 %>% full_join(qlongC3) %>% 
  rename(Vial = Ind)

save(qlong.acro, file = "qlong.acro.RData")
```
